# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import csv
import json
import time
import traceback
from multiprocessing import freeze_support
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

from ablation import add_head, add_layer, empty_cuda_cache, get_device_arg, parse_pretrained, str2bool


ROOT = Path(__file__).resolve().parent
DEFAULT_DATA = ROOT / "datasets" / "data.yaml"
DEFAULT_PROJECT = ROOT / "runs" / "rebuttal_pooling"
GENERATED_MODEL_DIR = ROOT / "ultralytics" / "cfg" / "models" / "v8" / "rebuttal_generated"

# mode, table label
VARIANTS: Dict[str, Tuple[str, str]] = {
    "gap": ("gap", "GAP"),
    "gmp": ("gmp", "GMP"),
    "gap_gmp": ("gap_gmp", "GAP+GMP"),
    "top1": ("top1", "Top-1 max peak"),
    "ppap": ("ppap", "PPAP top-k peak average"),
}


def build_model_cfg(pooling_mode: str) -> dict:
    backbone: List[list] = []

    add_layer(backbone, -1, 1, "Conv", [64, 3, 2])
    add_layer(backbone, -1, 1, "Conv", [128, 3, 2])
    p2 = add_layer(backbone, -1, 3, "C2f", [128, True])
    add_layer(backbone, -1, 1, "Conv", [256, 3, 2])
    p3 = add_layer(backbone, -1, 6, "C2f", [256, True])
    add_layer(backbone, -1, 1, "Conv", [512, 3, 2])
    p4 = add_layer(backbone, -1, 6, "C2f", [512, True])
    add_layer(backbone, -1, 1, "Conv", [1024, 3, 2])
    p5_pre = add_layer(backbone, -1, 3, "C2f", [1024, True])

    add_layer(backbone, -1, 1, "PoolingEMA", [pooling_mode, 8, 0.05, 8, 64, 1])
    sppf = add_layer(backbone, -1, 1, "SPPF", [1024, 5])

    sources = [p2, p3, p4, p5_pre, sppf]
    r3 = add_layer(backbone, sources, 1, "KDEHyperGraphFusion", [256, 1, 48, 0.1])
    r4 = add_layer(backbone, sources, 1, "KDEHyperGraphFusion", [512, 2, 48, 0.1])
    r5 = add_layer(backbone, sources, 1, "KDEHyperGraphFusion", [1024, 4, 48, 0.1])

    head: List[list] = []
    x = add_head(backbone, head, [r5, r4], 1, "CLAGRGCUFuse", [512])
    p4_td = add_head(backbone, head, x, 3, "C2f", [512])
    x = add_head(backbone, head, [p4_td, r3], 1, "CLAGRGCUFuse", [256])
    p3_out = add_head(backbone, head, x, 3, "C2f", [256])

    add_head(backbone, head, p3_out, 1, "Conv", [256, 3, 2])
    add_head(backbone, head, [-1, p4_td], 1, "Concat", [1])
    p4_out = add_head(backbone, head, -1, 3, "C2f", [512])

    add_head(backbone, head, p4_out, 1, "Conv", [512, 3, 2])
    add_head(backbone, head, [-1, r5], 1, "Concat", [1])
    p5_out = add_head(backbone, head, -1, 3, "C2f", [1024])

    add_head(backbone, head, [p3_out, p4_out, p5_out], 1, "Detect", ["nc"])

    return {
        "nc": 80,
        "scales": {
            "n": [0.33, 0.25, 1024],
            "s": [0.33, 0.50, 1024],
            "m": [0.67, 0.75, 768],
            "l": [1.00, 1.00, 512],
            "x": [1.00, 1.25, 512],
        },
        "backbone": backbone,
        "head": head,
    }


def dump_model_yaml(name: str, pooling_mode: str, label: str) -> Path:
    GENERATED_MODEL_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_MODEL_DIR / f"yolov8n_pooling_{name}.yaml"
    header = f"# Auto-generated by rebuttal_pooling_ablation.py\n# Pooling variant: {label}\n"
    path.write_text(header + json.dumps(build_model_cfg(pooling_mode), indent=2), encoding="utf-8")
    return path


def select_variants(items: Iterable[str]) -> List[str]:
    requested = list(items)
    if not requested or requested == ["all"]:
        return list(VARIANTS.keys())
    result: List[str] = []
    for item in requested:
        key = item.strip().lower().replace("-", "_").replace("+", "_")
        if key == "all":
            expanded = list(VARIANTS.keys())
        else:
            if key not in VARIANTS:
                raise ValueError(f"unknown pooling variant '{item}', valid values: {', '.join(VARIANTS)}")
            expanded = [key]
        for value in expanded:
            if value not in result:
                result.append(value)
    return result


def append_summary(summary_csv: Path, row: dict) -> None:
    summary_csv.parent.mkdir(parents=True, exist_ok=True)
    fields = ["variant", "pooling_mode", "pooling_label", "status", "model_yaml", "save_dir", "seed", "error"]
    exists = summary_csv.exists()
    with summary_csv.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        if not exists:
            writer.writeheader()
        writer.writerow(row)


def run_variant(name: str, model_yaml: Path, args, seed: int):
    from ultralytics import YOLO

    model = YOLO(str(model_yaml))
    return model.train(
        data=str(args.data),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        workers=args.workers,
        device=get_device_arg(args.device),
        project=str(args.project),
        name=f"{args.name_prefix}_{name}_seed{seed}",
        exist_ok=args.exist_ok,
        pretrained=parse_pretrained(args.pretrained),
        save=True,
        save_period=args.save_period,
        cache=args.cache,
        patience=args.patience if args.patience is not None else args.epochs,
        seed=seed,
        deterministic=args.deterministic,
        verbose=True,
        resume=False,
        amp=args.amp,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run PPAP-EMA pooling replacement ablations.")
    parser.add_argument("--variants", nargs="*", default=["all"], help="all, gap, gmp, gap_gmp, top1, ppap")
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--project", type=Path, default=DEFAULT_PROJECT)
    parser.add_argument("--name-prefix", default="pooling")
    parser.add_argument("--epochs", type=int, default=500)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--seed", type=int, default=4401)
    parser.add_argument("--pretrained", default="True")
    parser.add_argument("--save-period", type=int, default=10)
    parser.add_argument("--patience", type=int, default=None)
    parser.add_argument("--cache", action="store_true")
    parser.add_argument("--exist-ok", action="store_true")
    parser.add_argument("--deterministic", type=str2bool, default=True)
    parser.add_argument("--amp", type=str2bool, default=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    variants = select_variants(args.variants)
    args.project.mkdir(parents=True, exist_ok=True)
    summary_csv = args.project / "pooling_ablation_summary.csv"

    print("PPAP-EMA pooling ablation")
    print("Data:", args.data)
    print("Project:", args.project)
    print("Variants:", ", ".join(variants))

    for offset, name in enumerate(variants):
        pooling_mode, label = VARIANTS[name]
        model_yaml = dump_model_yaml(name, pooling_mode, label)
        seed = args.seed + offset
        print("\n" + "=" * 90)
        print(f"Variant {name}: {label}")
        print("Model YAML:", model_yaml)
        print("Seed:", seed)
        print("=" * 90)

        if args.dry_run:
            continue

        row = {
            "variant": name,
            "pooling_mode": pooling_mode,
            "pooling_label": label,
            "status": "failed",
            "model_yaml": str(model_yaml),
            "save_dir": "",
            "seed": seed,
            "error": "",
        }
        try:
            results = run_variant(name, model_yaml, args, seed)
            save_dir = getattr(getattr(results, "trainer", None), "save_dir", "")
            row["save_dir"] = str(save_dir)
            row["status"] = "ok"
            append_summary(summary_csv, row)
            empty_cuda_cache()
            time.sleep(5)
        except Exception as exc:
            row["error"] = repr(exc)
            append_summary(summary_csv, row)
            traceback.print_exc()
            empty_cuda_cache()
            time.sleep(5)


if __name__ == "__main__":
    freeze_support()
    main()
